"use client"

export default function Home() {
  return (
    <>
      <p className="">
        hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus. hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus.hola Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias minima iusto sunt libero quidem praesentium inventore, doloribus deserunt provident ut perspiciatis nulla enim ea dolor rerum autem, maxime necessitatibus.
      </p>
    </>
  );
}
